// tools/build.mjs
//
// Generate docs/ — the GitHub Pages wiki — from tools/data.json plus the
// prose in content.mjs.
//
//   node tools/build.mjs
//
// data.json is written by dump_main.lua straight off the working tree, so
// regenerating after a balance change is two commands and the page cannot
// drift from the game. See README.md.

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as C from "./content.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const DOCS = join(ROOT, "docs");

const D = JSON.parse(readFileSync(join(HERE, "data.json"), "utf8"));

/* ── Helpers ─────────────────────────────────────────────────────────── */
const esc = (s) =>
  String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

// An id that is stable across rebuilds and safe in a URL fragment, so a link
// someone shared six months ago still lands on the same row.
const slug = (s) =>
  String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const pct = (v, base = 1) => {
  if (v == null) return null;
  const n = Math.round((v - base) * 100);
  return (n > 0 ? "+" : "") + n + "%";
};

const RARITY_ORDER = ["common", "uncommon", "rare", "epic", "legendary"];
const NAME_BY_KEY = Object.fromEntries(D.upgrades.map((u) => [u.k, u.n]));
const ENEMY_BY_KEY = Object.fromEntries(D.enemies.map((e) => [e.k, e]));

// Everything a reader might type, lowercased, per row.
const hay = (...parts) => esc(parts.filter(Boolean).join(" ").toLowerCase());

/* ── Search index ────────────────────────────────────────────────────── */
const INDEX = [];
const idx = (n, section, page, anchor, key, extra) =>
  INDEX.push({ n, s: section, u: `${page}#${anchor}`, k: key || "", h: [n, key, extra].filter(Boolean).join(" ").toLowerCase() });

/* ── Page shell ──────────────────────────────────────────────────────── */
function page({ file, title, lead, toc = [], body, wide = false }) {
  const nav = C.NAV.map(
    (n) =>
      `<a href="${n.file}"${n.file === file ? ' aria-current="page"' : ""}><em>${n.icon}</em>${esc(n.label)}</a>`
  ).join("\n        ");

  const tocHtml = toc.length
    ? `<div class="side-head">On this page</div>
        <div class="toc">${toc.map((t) => `<a href="#${t.id}">${esc(t.label)}</a>`).join("")}</div>`
    : "";

  return `<!DOCTYPE html>
<html lang="en" data-page="${slug(file)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)} · ${esc(C.SITE.title)}</title>
<meta name="description" content="${esc(lead)}">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><text y='26' font-size='26'>&#128302;</text></svg>">
<link rel="stylesheet" href="assets/wiki.css">
<script>
/* Applied before first paint so the page never flashes the wrong scheme. */
try { var t = localStorage.getItem("rr-theme"); if (t) document.documentElement.setAttribute("data-theme", t); } catch (e) {}
</script>
</head>
<body data-page="${slug(file)}">

<header class="topbar">
  <button class="menu-btn" id="menu-btn" aria-label="Menu">☰</button>
  <a class="brand" href="index.html"><b>${esc(C.SITE.title)}</b><span>wiki</span></a>
  <div class="search-wrap">
    <input id="site-search" type="search" placeholder="Search everything…  ( / )" autocomplete="off" aria-label="Search the wiki">
    <div id="search-results" role="listbox"></div>
  </div>
  <button class="theme-btn" id="theme-btn" aria-label="Toggle colour scheme">◐</button>
</header>

<div class="shell">
  <aside class="sidebar" id="sidebar">
    <nav>
        ${nav}
    </nav>
    ${tocHtml}
  </aside>

  <main>
    <div class="page-head">
      <h1>${esc(title)}</h1>
      <p>${lead}</p>
    </div>
${body}
    <footer>
      Generated by <code>Tools/wiki/build.mjs</code> from the game's own definition tables. Every
      number on this page is dumped out of the source — nothing here is typed by hand twice.
      The game's repository is private; this site is published from a separate public one.
      <br>
      <a href="${C.SITE.repo}">${esc(C.SITE.repoLabel || "This site on GitHub")}</a> ·
      <a href="index.html">Wiki home</a>
    </footer>
  </main>
</div>

<script src="assets/search.js"></script>
<script src="assets/wiki.js"></script>
</body>
</html>
`;
}

/* A search box + chip row + hit counter, for the list pages. */
function toolbar(placeholder, chips = []) {
  return `<div class="toolbar">
      <input class="filter" id="page-filter" type="search" placeholder="${esc(placeholder)}" autocomplete="off" aria-label="Filter this page">
      <div id="page-chips">${chips
        .map((c) => `<button type="button" class="chip" data-attr="${c.attr}" aria-pressed="false">${esc(c.label)}</button>`)
        .join("")}</div>
      <span class="hits" id="page-hits"></span>
    </div>`;
}
const EMPTY = `<div class="empty" id="page-empty" hidden>Nothing matches the current filters.</div>`;

/* ═══════════════════════════════════════════════════════════════════════
   Home
   ═══════════════════════════════════════════════════════════════════ */
function homePage() {
  const counts = [
    [D.enemies.length, "enemies"],
    [D.upgrades.length, "cards"],
    [D.abilities.length, "abilities"],
    [D.archetypes.length, "classes"],
    [D.modifiers.length, "modifiers"],
    [D.compositions.length, "designed waves"],
    [D.achievements.length, "achievements"],
    [D.consts.bossRotation.length, "bosses"],
  ];

  const tiles = C.NAV.filter((n) => n.file !== "index.html")
    .map((n) => {
      const blurb = {
        "guide.html": "Controls, the run loop, and what the orb actually does.",
        "bestiary.html": "Every enemy, what drives it, and when it starts appearing.",
        "bosses.html": "The two boss fights, attack by attack.",
        "cards.html": `All ${D.upgrades.length} upgrade cards, with stack caps, prerequisites and exclusions.`,
        "abilities.html": "The twelve F-key abilities, and how they measured against each other.",
        "classes.html": "The four starting classes, and the benchmark that set them.",
        "waves.html": "Difficulty, modifiers, designed waves, elites and the boss rotation.",
        "achievements.html": `All ${D.achievements.length}, including the hidden ones.`,
        "systems.html": "Damage, drops, score and sound — how the machinery fits together.",
      }[n.file];
      return `<a class="tile" href="${n.file}"><b>${n.icon} ${esc(n.label)}</b><span>${esc(blurb)}</span></a>`;
    })
    .join("\n      ");

  const loop = C.LOOP.map((l) => `<h3>${esc(l.h)}</h3>\n    <p>${l.p}</p>`).join("\n    ");

  const body = `    <div class="counts">
      ${counts.map(([n, l]) => `<div class="count"><b>${n}</b><span>${esc(l)}</span></div>`).join("\n      ")}
    </div>

    <div class="tiles">
      ${tiles}
    </div>

    <h2 id="what">What the game is</h2>
    ${loop}

    <div class="note">
      <b>This wiki is generated, not written.</b> Every stat, cost, cooldown, weight, cap and
      prerequisite on these pages is dumped out of the game's own definition tables by a script in
      the repository. The prose around them is hand-written; the numbers never are. If a number
      here is wrong, the game is wrong.
    </div>

    <h2 id="glossary">Glossary</h2>
    <table>
      <thead><tr><th>Term</th><th>Meaning</th></tr></thead>
      <tbody>
        ${C.GLOSSARY.map((g) => `<tr><td>${esc(g.t)}</td><td>${esc(g.d)}</td></tr>`).join("\n        ")}
      </tbody>
    </table>`;

  return page({
    file: "index.html",
    title: "Ricochet Ritual",
    lead: esc(C.SITE.tagline) + " You get one orb. Everything else is a consequence of that.",
    toc: [
      { id: "what", label: "What the game is" },
      { id: "glossary", label: "Glossary" },
    ],
    body,
  });
}

/* ═══════════════════════════════════════════════════════════════════════
   How to play
   ═══════════════════════════════════════════════════════════════════ */
function guidePage() {
  const u = D.consts.upgrade;
  const p = D.consts.pickup;

  const controls = C.CONTROLS.map(
    (c) =>
      `<tr><td><code>${esc(c.key)}</code></td><td>${esc(c.act)}</td><td>${esc(c.note || "")}</td></tr>`
  ).join("\n        ");

  const diffs = D.difficulties
    .map((d) => {
      const cells = [
        ["enemy health", pct(d.healthMult)],
        ["enemy damage", pct(d.damageMult)],
        ["enemy speed", pct(d.speedMult)],
        ["scaling rate", pct(d.rampMult)],
        ["spawn interval", pct(d.spawnIntervalMult)],
        ["concurrent cap", pct(d.maxAliveMult)],
      ]
        .filter(([, v]) => v && v !== "+0%")
        .map(([l, v]) => `<div class="per">${esc(l)} <span class="tot">${v}</span></div>`)
        .join("");
      return `<div class="row" id="diff-${slug(d.id)}" style="--stripe:var(--${
        d.id === "easy" ? "uncommon" : d.id === "hard" ? "warn" : "rare"
      })" data-hay="${hay(d.id, d.n, d.d, d.tag)}">
        <div class="r-name" data-anchor><span>${esc(d.n)}</span><span class="r-key">${esc(d.id)}</span></div>
        <div class="r-desc"><div>${esc(d.d)}</div><div class="tot">${esc(d.tag)}</div></div>
        <div class="r-meta">${cells}
          <div class="dep">heals ${Math.round(d.healFrac * 100)}%${
        d.healFlat ? ` + ${d.healFlat}` : ""
      } between waves</div>
          <div class="dep">${d.rerolls} rerolls · ${d.banishes} banishes</div>
        </div>
      </div>`;
    })
    .join("\n      ");

  for (const d of D.difficulties) idx(d.n, "Difficulty", "guide.html", `diff-${slug(d.id)}`, d.id, d.d);

  const body = `    <h2 id="controls">Controls</h2>
    <table>
      <thead><tr><th>Input</th><th>Does</th><th></th></tr></thead>
      <tbody>
        ${controls}
      </tbody>
    </table>

    <h2 id="loop">The run</h2>
    ${C.LOOP.map((l) => `<h3>${esc(l.h)}</h3>\n    <p>${l.p}</p>`).join("\n    ")}

    <h2 id="upgrades">The upgrade screen</h2>
    <p>
      Clearing a wave opens it. You are offered two cards, and on every
      <b>${u.UTILITY_EVERY}${u.UTILITY_EVERY === 3 ? "rd" : "th"}</b> screen a further card that is
      a <a href="abilities.html">utility ability</a> rather than a passive — you carry one of those
      at a time, so taking a second replaces the first.
    </p>
    <p>
      <b>Rerolls</b> redraw the screen; <b>banishes</b> remove a card from the pool for the rest of
      the run. Both accumulate on a timer rather than being spent currency: you gain a reroll every
      <b>${u.REROLL_EVERY_WAVES}</b> waves and a banish every <b>${u.BANISH_EVERY_WAVES}</b>,
      capped at <b>${u.REROLL_CAP}</b> and <b>${u.BANISH_CAP}</b>. A bad screen late in a run is
      therefore a much smaller disaster than a bad screen early, which is the intent — the early
      screens are where a build is decided.
    </p>
    <p>
      Rarity is a draw weight, not a power ranking. A card is offered in proportion to it:
      ${RARITY_ORDER.map((r) => `<code>${r} ${D.consts.rarityWeight[r]}</code>`).join(" · ")}.
      Cards at their stack cap, cards whose prerequisite you do not own, and cards that conflict
      with something you already took are all removed from the draw rather than offered and
      wasted.
    </p>

    <h2 id="drops">Staying alive</h2>
    <p>
      Bodies drop hearts, and the chance depends on how badly you need one — it reads your health
      <b>fraction</b>, so the field stays clean while you are healthy and starts paying out when
      you are not.
    </p>
    <table>
      <thead><tr><th>When</th><th>Chance</th><th></th></tr></thead>
      <tbody>
        ${C.DROPS.map(
          (d) => `<tr><td>${esc(d.n)}</td><td><code>${esc(d.rate)}</code> ${esc(d.per)}</td><td>${esc(d.d)}</td></tr>`
        ).join("\n        ")}
      </tbody>
    </table>
    <p class="tot">
      A heart lives <b>${p.LIFETIME}s</b>, flashes for the last <b>${p.BLINK_AT}s</b>, drifts to
      you inside <b>${p.MAGNET_RANGE}px</b> at <b>${p.MAGNET_SPEED}px/s</b> and is collected at
      <b>${p.PICKUP_RANGE}px</b>. At most <b>${p.MAX_ACTIVE}</b> sit on the field at once, so a
      wipe in a big wave cannot carpet the ground.
    </p>
    <div class="note">${C.DROP_NOTE}</div>

    <h2 id="difficulty">Difficulty</h2>
    <p>
      Picked before the class, at the start of a run, and locked for its duration — changing the
      menu mid-run cannot rewrite what you are playing. Records store the difficulty alongside the
      score, because a HARD score and an EASY score are not the same number.
    </p>
    <div class="rows">
      ${diffs}
    </div>`;

  return page({
    file: "guide.html",
    title: "How to play",
    lead: "One orb, thrown and recalled. Everything below follows from that.",
    toc: [
      { id: "controls", label: "Controls" },
      { id: "loop", label: "The run" },
      { id: "upgrades", label: "The upgrade screen" },
      { id: "drops", label: "Staying alive" },
      { id: "difficulty", label: "Difficulty" },
    ],
    body,
  });
}

/* ═══════════════════════════════════════════════════════════════════════
   Bestiary
   ═══════════════════════════════════════════════════════════════════ */
function bestiaryPage() {
  const ordinary = D.enemies.filter((e) => !e.x.is_boss).sort((a, b) => (a.unlock ?? 99) - (b.unlock ?? 99) || a.k.localeCompare(b.k));
  const bosses = D.enemies.filter((e) => e.x.is_boss);

  // Which types share a sheet, so a recoloured variant can say so.
  const bySheet = {};
  for (const e of D.enemies) {
    if (!e.sheet) continue;
    (bySheet[e.sheet] ||= []).push(e.k);
  }

  function beast(e) {
    const ai = C.AI[e.ai] || { label: e.ai || "—", tone: "common", p: "" };
    const stats = [];
    stats.push(`<span class="stat">HP <b>${e.hp}</b></span>`);
    stats.push(`<span class="stat">speed <b>${e.spd}</b></span>`);
    if (e.dmg) stats.push(`<span class="stat">damage <b>${e.dmg}</b></span>`);
    if (e.range) stats.push(`<span class="stat">range <b>${e.range}</b></span>`);
    if (e.br) stats.push(`<span class="stat">blast <b>${e.br}</b> for <b>${e.bd}</b></span>`);
    if (e.proj) stats.push(`<span class="stat">fires <b>${esc(e.proj)}</b></span>`);
    if (e.unlock) stats.push(`<span class="stat">from wave <b>${e.unlock}</b></span>`);
    if (e.weight) stats.push(`<span class="stat">weight <b>${e.weight}</b></span>`);
    if (e.cap) stats.push(`<span class="stat">max <b>${e.cap}</b> alive</span>`);
    stats.push(`<span class="stat">hitbox <b>${e.rx}×${e.ry}</b></span>`);

    // A shared sheet means one of these is the ORIGINAL and the rest are
    // recolours of it. Saying "shares art with" on both sides reads as though
    // neither owns the sprite, and leaves the base enemy claiming it is told
    // apart by a recolour it does not have.
    const isRecolour = !!(e.hue || e.tint);
    const shares = (bySheet[e.sheet] || []).filter((k) => k !== e.k);
    const how = e.tint ? "a colour tint" : "a hue rotation";
    const shareLine = !shares.length
      ? ""
      : isRecolour
      ? `<p class="tot">A recolour of ${shares
          .filter((k) => !ENEMY_BY_KEY[k].hue && !ENEMY_BY_KEY[k].tint)
          .map((k) => `<a href="#${slug(k)}">${esc(k)}</a>`)
          .join(", ") || "the shared sheet"}'s art, told apart by ${how}.</p>`
      : `<p class="tot">The original art. ${shares
          .map((k) => `<a href="#${slug(k)}">${esc(k)}</a>`)
          .join(", ")} ${shares.length > 1 ? "are recolours" : "is a recolour"} of it.</p>`;

    const extra = C.ENEMY_EXTRA[e.k] ? `<p class="tot">${C.ENEMY_EXTRA[e.k]}</p>` : "";
    const bossLink = e.x.is_boss ? ` <a href="bosses.html#${slug(e.k)}" class="tot">full fight →</a>` : "";

    return `<div class="beast" id="${slug(e.k)}" style="--stripe:var(--${ai.tone})"
        data-hay="${hay(e.k, ai.label, C.ENEMY_NOTE[e.k], e.proj, "wave " + e.unlock)}"
        data-boss="${e.x.is_boss ? 1 : 0}" data-ranged="${e.range >= 200 ? 1 : 0}"
        data-variant="${isRecolour ? 1 : 0}">
        <div class="portrait"><img src="assets/img/${esc(e.k)}.png" alt="${esc(e.k)}" loading="lazy" width="82"></div>
        <div class="beast-body">
          <div class="beast-head" data-anchor>
            <h3>${esc(e.x.boss_name || e.k)}</h3>
            <span class="badge">${esc(ai.label)}</span>
            ${e.x.boss_name ? `<span class="badge plain">${esc(e.k)}</span>` : ""}
            ${bossLink}
          </div>
          <p>${esc(C.ENEMY_NOTE[e.k] || "")}</p>
          <div class="statline">${stats.join("")}</div>
          ${shareLine}${extra}
        </div>
      </div>`;
  }

  for (const e of D.enemies) {
    idx(e.x.boss_name || e.k, "Bestiary", "bestiary.html", slug(e.k), e.k, C.ENEMY_NOTE[e.k]);
  }

  const aiUsed = [...new Set(D.enemies.map((e) => e.ai))].filter((a) => C.AI[a]);
  const aiRows = aiUsed
    .map((a) => {
      const c = C.AI[a];
      const members = D.enemies.filter((e) => e.ai === a).map((e) => `<a href="#${slug(e.k)}">${esc(e.k)}</a>`);
      return `<div class="row" id="ai-${slug(a)}" style="--stripe:var(--${c.tone})" data-hay="${hay(a, c.label, c.p)}">
        <div class="r-name" data-anchor><span>${esc(c.label)}</span><span class="r-key">${esc(a)}</span></div>
        <div class="r-desc">${c.p}</div>
        <div class="r-meta"><div class="per">${members.join(", ")}</div></div>
      </div>`;
    })
    .join("\n      ");

  // Two classes share the label "Boss", so index them by MODULE name — a
  // search result that cannot tell you which of two things it found is worse
  // than no result.
  for (const a of aiUsed) {
    const dup = aiUsed.filter((x) => C.AI[x].label === C.AI[a].label).length > 1;
    idx(dup ? `${C.AI[a].label} AI (${a})` : `${C.AI[a].label} AI`,
        "Behaviour", "bestiary.html", `ai-${slug(a)}`, a, C.AI[a].p);
  }

  const body = `    ${toolbar("Filter enemies…", [
      { attr: "boss", label: "bosses" },
      { attr: "ranged", label: "ranged" },
      { attr: "variant", label: "recolours" },
    ])}

    <h2 id="roster">The roster</h2>
    <p>
      Ordered by the wave they start appearing on. <b>Weight</b> is how often a type is drawn once
      it has unlocked, relative to everything else eligible — the behaviour enemies are deliberately
      rare, because a wave that is half Ravagers is not six times as interesting as a wave with one
      in it.
    </p>
    <div class="rows">
      ${ordinary.map(beast).join("\n      ")}
    </div>

    <h2 id="bosses">Bosses</h2>
    <p>Exempt from wave modifiers' health multipliers, and never elite. <a href="bosses.html">The fights in full →</a></p>
    <div class="rows">
      ${bosses.map(beast).join("\n      ")}
    </div>

    <h2 id="behaviour">Behaviour classes</h2>
    <p>
      What actually drives each type. Several enemies share a class and differ only in their stat
      block — a Nosferatu is a Vampire with different numbers — and that is the cheap half of the
      roster. The rest have their own code.
    </p>
    <div class="rows">
      ${aiRows}
    </div>
    ${EMPTY}`;

  return page({
    file: "bestiary.html",
    title: "Bestiary",
    lead: `All ${D.enemies.length} enemy types, with the AI that drives each one. Portraits are rendered through the game's own recolour shader, so a variant looks here exactly as it does in play.`,
    toc: [
      { id: "roster", label: "The roster" },
      { id: "bosses", label: "Bosses" },
      { id: "behaviour", label: "Behaviour classes" },
    ],
    body,
  });
}

/* ═══════════════════════════════════════════════════════════════════════
   Bosses
   ═══════════════════════════════════════════════════════════════════ */
function bossesPage() {
  const rot = D.consts.bossRotation;

  const sections = rot
    .map((key, i) => {
      const e = ENEMY_BY_KEY[key];
      const b = C.BOSSES[key];
      if (!e || !b) return "";
      idx(e.x.boss_name || key, "Bosses", "bosses.html", slug(key), key, b.lead);
      const stats = [
        `<span class="stat">base HP <b>${e.hp}</b></span>`,
        `<span class="stat">speed <b>${e.spd}</b></span>`,
        `<span class="stat">contact <b>${e.dmg}</b></span>`,
        `<span class="stat">hitbox <b>${e.rx}×${e.ry}</b></span>`,
        `<span class="stat">scale <b>×${e.scale}</b></span>`,
      ].join("");
      return `    <h2 id="${slug(key)}">${esc(e.x.boss_name || key)}</h2>
    <div class="beast" style="--stripe:var(--legendary)">
      <div class="portrait"><img src="assets/img/${esc(key)}.png" alt="${esc(key)}" loading="lazy" width="82"></div>
      <div class="beast-body">
        <div class="beast-head">
          <h3>${esc(b.sub)}</h3>
          <span class="badge">${esc((C.AI[e.ai] || {}).label || "Boss")}</span>
        </div>
        <p>${b.lead}</p>
        <div class="statline">${stats}</div>
      </div>
    </div>
    <table>
      <thead><tr><th>Move</th><th>What it does</th></tr></thead>
      <tbody>
        ${b.moves.map((m) => `<tr><td>${esc(m.n)}</td><td>${m.d}</td></tr>`).join("\n        ")}
      </tbody>
    </table>
    <p>${b.close}</p>`;
    })
    .join("\n\n");

  const body = `    <div class="note">${C.BOSS_SHARED}</div>

    <h2 id="rotation">The rotation</h2>
    <p>
      A boss arrives every tenth wave and the order is fixed, cycling through
      ${rot.length} of them:
    </p>
    <table>
      <thead><tr><th>Wave</th><th>Boss</th><th></th></tr></thead>
      <tbody>
        ${rot
          .map((k, i) => {
            const e = ENEMY_BY_KEY[k];
            return `<tr><td>${(i + 1) * 10}, ${(i + 1) * 10 + rot.length * 10}, …</td><td><a href="#${slug(
              k
            )}">${esc(e?.x.boss_name || k)}</a></td><td>${esc(C.ENEMY_NOTE[k] || "")}</td></tr>`;
          })
          .join("\n        ")}
      </tbody>
    </table>

${sections}`;

  return page({
    file: "bosses.html",
    title: "Bosses",
    lead: "Two fights, deliberately opposite. One asks you to read it; the other asks you to already be moving.",
    toc: [{ id: "rotation", label: "The rotation" }].concat(
      rot.map((k) => ({ id: slug(k), label: ENEMY_BY_KEY[k]?.x.boss_name || k }))
    ),
    body,
  });
}

/* ═══════════════════════════════════════════════════════════════════════
   Cards
   ═══════════════════════════════════════════════════════════════════ */
function cardsPage() {
  const byRarity = {};
  for (const u of D.upgrades) (byRarity[u.rarity || u.r] ||= []).push(u);

  const groups = RARITY_ORDER.map((r) => {
    const list = (byRarity[r] || []).sort((a, b) => a.n.localeCompare(b.n));
    if (!list.length) return "";
    const rows = list
      .map((u) => {
        idx(u.n, "Cards", "cards.html", slug(u.k), u.k, u.d);
        const meta = [];
        if (u.s) {
          meta.push(
            `<div class="per">stackable${u.cap ? ` · <b>cap ${u.cap}</b>` : " · <b>no cap</b>"}</div>`
          );
        }
        if (u.val != null && u.v) {
          meta.push(`<div class="tot"><code>${esc(u.v)}</code> ${u.t === "ADD" ? "+" : "="}${u.val}</div>`);
        } else if (u.v) {
          meta.push(`<div class="tot"><code>${esc(u.v)}</code></div>`);
        }
        if (u.req) {
          meta.push(
            `<div class="dep">needs <a href="#${slug(u.req)}"><b>${esc(NAME_BY_KEY[u.req] || u.req)}</b></a></div>`
          );
        }
        if (u.con) {
          meta.push(
            `<div class="dep flag">excludes ${u.con
              .map((c) => `<a href="#${slug(c)}"><b>${esc(NAME_BY_KEY[c] || c)}</b></a>`)
              .join(", ")}</div>`
          );
        }
        const note = C.CARD_NOTE[u.k];
        return `<div class="row" id="${slug(u.k)}" style="--stripe:var(--${r})"
          data-hay="${hay(u.k, u.n, u.d, u.v, r, note)}"
          data-stackable="${u.s ? 1 : 0}" data-req="${u.req ? 1 : 0}" data-con="${u.con ? 1 : 0}">
          <div class="r-name" data-anchor><span>${esc(u.n)}</span><span class="r-key">${esc(u.k)}</span></div>
          <div class="r-desc">${esc(u.d)}${note ? `<div class="tot">${esc(note)}</div>` : ""}</div>
          <div class="r-meta">${meta.join("")}</div>
        </div>`;
      })
      .join("\n      ");
    return `<div class="group-label" id="${slug(r)}">${r} <span style="opacity:.6">· ${list.length} cards · draw weight ${D.consts.rarityWeight[r]}</span></div>
      ${rows}`;
  }).join("\n      ");

  const stackable = D.upgrades.filter((u) => u.s).length;
  const capped = D.upgrades.filter((u) => u.cap).length;
  const gated = D.upgrades.filter((u) => u.req).length;
  const exclusive = D.upgrades.filter((u) => u.con).length;

  const body = `    <div class="counts">
      <div class="count"><b>${D.upgrades.length}</b><span>cards</span></div>
      <div class="count"><b>${stackable}</b><span>stackable</span></div>
      <div class="count"><b>${capped}</b><span>with a cap</span></div>
      <div class="count"><b>${gated}</b><span>need a prereq</span></div>
      <div class="count"><b>${exclusive}</b><span>mutually exclusive</span></div>
    </div>

    ${toolbar("Filter cards by name, effect or stat key…", [
      { attr: "stackable", label: "stackable" },
      { attr: "req", label: "has prereq" },
      { attr: "con", label: "exclusive" },
    ])}

    <div class="note">
      <b>Rarity is a draw weight, not a power ranking.</b> A legendary is not strictly better than a
      rare — it is rarer, which usually means it changes how a build works rather than how big its
      numbers are. Cards are removed from the draw entirely when they cannot help you: at their
      stack cap, missing a prerequisite, or conflicting with something you already own. Being
      offered a card that does nothing is worse than being offered nothing.
    </div>

    <div class="rows">
      ${groups}
    </div>
    ${EMPTY}`;

  return page({
    file: "cards.html",
    title: "Upgrade cards",
    lead: `All ${D.upgrades.length} of them, grouped by rarity. Stack caps, prerequisites and exclusions are read out of the upgrade manager rather than transcribed.`,
    toc: RARITY_ORDER.filter((r) => byRarity[r]).map((r) => ({ id: slug(r), label: r })),
    body,
  });
}

/* ═══════════════════════════════════════════════════════════════════════
   Abilities
   ═══════════════════════════════════════════════════════════════════ */
function abilitiesPage() {
  const rows = [...D.abilities]
    .sort((a, b) => a.cd - b.cd)
    .map((a) => {
      idx(a.n, "Abilities", "abilities.html", slug(a.id), a.id, a.d);
      const m = C.ABI_MEASURED[a.id];
      const meta = [`<div class="per">${a.cd}s cooldown</div>`];
      meta.push(`<div class="tot">${a.dur ? `${a.dur}s active` : "instant"}</div>`);
      if (m) {
        meta.push(`<div class="per"><b>${m.kills}</b> kills/cast</div>`);
        meta.push(`<div class="tot">${m.per} per second of cooldown</div>`);
        if (m.was) meta.push(`<div class="dep flag">was <b>${m.was}</b> before the retune</div>`);
        if (m.note) meta.push(`<div class="dep">${esc(m.note)}</div>`);
      } else {
        meta.push(`<div class="dep">no damage — judged behaviourally</div>`);
      }
      return `<div class="row" id="${slug(a.id)}" style="--stripe:var(--legendary)"
        data-hay="${hay(a.id, a.n, a.d)}" data-damaging="${m ? 1 : 0}">
        <div class="r-name" data-anchor><span>${esc(a.n)}</span><span class="r-key">${esc(a.id)}</span></div>
        <div class="r-desc">${esc(a.d)}</div>
        <div class="r-meta">${meta.join("")}</div>
      </div>`;
    })
    .join("\n      ");

  const u = D.consts.upgrade;
  const body = `    ${toolbar("Filter abilities…", [{ attr: "damaging", label: "damaging" }])}

    <p>
      Bound to <code>F</code>. You carry exactly one, and one is offered as an extra card on every
      <b>${u.UTILITY_EVERY}${u.UTILITY_EVERY === 3 ? "rd" : "th"}</b> upgrade screen — taking a new
      one replaces what you had.
    </p>

    <div class="rows">
      ${rows}
    </div>
    ${EMPTY}

    <h2 id="balance">How these were balanced</h2>
    <div class="note">${C.ABI_NOTE}</div>

    <h3>Kills per cast, and per second of cooldown</h3>
    <table>
      <thead><tr><th>Ability</th><th>Kills / cast</th><th>Per second of cooldown</th><th></th></tr></thead>
      <tbody>
        ${Object.entries(C.ABI_MEASURED)
          .map(([id, m]) => {
            const a = D.abilities.find((x) => x.id === id);
            return `<tr><td><a href="#${slug(id)}">${esc(a ? a.n : id)}</a></td><td><code>${m.kills}</code></td><td><code>${
              m.per
            }</code></td><td>${esc(m.note || (m.was ? `was ${m.was}` : ""))}</td></tr>`;
          })
          .join("\n        ")}
      </tbody>
    </table>`;

  return page({
    file: "abilities.html",
    title: "Utility abilities",
    lead: "Twelve buttons on a long cooldown. Five of them do damage, and those five were measured against each other rather than tuned by eye.",
    toc: [{ id: "balance", label: "How these were balanced" }],
    body,
  });
}

/* ═══════════════════════════════════════════════════════════════════════
   Classes
   ═══════════════════════════════════════════════════════════════════ */
function classesPage() {
  const rows = D.archetypes
    .map((a) => {
      idx(a.n, "Classes", "classes.html", slug(a.id), a.id, a.d);
      const m = C.ARCH_MEASURED[a.id] || {};
      const counts = {};
      for (const g of a.grant) counts[g] = (counts[g] || 0) + 1;
      const opener = Object.entries(counts)
        .map(([k, n]) => `<a href="cards.html#${slug(k)}">${esc(NAME_BY_KEY[k] || k)}</a>${n > 1 ? ` ×${n}` : ""}`)
        .join(", ");
      const bias = a.bias
        .map((b) => `<a href="cards.html#${slug(b.k)}">${esc(NAME_BY_KEY[b.k] || b.k)}</a>`)
        .join(", ");
      const meta = [];
      if (m.dmg) meta.push(`<div class="per">damage <b>${m.dmg}</b></div>`);
      if (m.live) meta.push(`<div class="per">survival <b>${m.live}</b></div>`);
      if (m.blind) meta.push(`<div class="dep flag"><b>the fixture cannot see this class</b></div>`);
      meta.push(`<div class="dep">${a.bias.length} cards biased</div>`);

      const rgb = (a.col || [1, 1, 1]).map((c) => Math.round(c * 255)).join(",");
      return `<div class="row" id="${slug(a.id)}" style="--stripe:rgb(${rgb})"
        data-hay="${hay(a.id, a.n, a.d, a.tag, a.bias.map((b) => b.k).join(" "))}">
        <div class="r-name" data-anchor><span>${esc(a.n)}</span><span class="r-key">${esc(a.id)}</span></div>
        <div class="r-desc">
          <div>${esc(a.d)}</div>
          <div class="tot">${esc(a.tag)}</div>
          <div class="per">opens with <b>${opener}</b></div>
          <div class="tot">biased toward: ${bias}</div>
        </div>
        <div class="r-meta">${meta.join("")}</div>
      </div>`;
    })
    .join("\n      ");

  const body = `    <p>
      Picked once, after the difficulty, before the first wave. A class is not new content — it is
      a <b>weighting</b>. Each one multiplies the draw weight of about a dozen cards that already
      exist, so a Stormcaller run finds its chain pieces early and a Warden run finds its armour.
      The pool is never restricted: every card can still appear for every class, so the bias steers
      a run without railroading it, and taking the off-class card you were offered stays a real
      decision.
    </p>

    ${toolbar("Filter classes…")}
    <div class="rows">
      ${rows}
    </div>
    ${EMPTY}

    <h2 id="balance">How these were balanced</h2>
    <div class="note">${C.ARCH_NOTE}</div>

    <table>
      <thead><tr><th>Class</th><th>Damage</th><th>Survival</th><th></th></tr></thead>
      <tbody>
        ${D.archetypes
          .map((a) => {
            const m = C.ARCH_MEASURED[a.id] || {};
            return `<tr><td><a href="#${slug(a.id)}">${esc(a.n)}</a></td><td><code>${esc(
              m.dmg || "—"
            )}</code></td><td><code>${esc(m.live || "—")}</code></td><td>${
              m.blind ? "measured as noise — the fixture is stationary" : ""
            }</td></tr>`;
          })
          .join("\n        ")}
      </tbody>
    </table>`;

  return page({
    file: "classes.html",
    title: "Classes",
    lead: `${D.archetypes.length} starting classes. None of them is the correct pick, and that was checked rather than assumed.`,
    toc: [{ id: "balance", label: "How these were balanced" }],
    body,
  });
}

/* ═══════════════════════════════════════════════════════════════════════
   Waves
   ═══════════════════════════════════════════════════════════════════ */
function wavesPage() {
  const mods = D.modifiers
    .map((m) => {
      idx(m.n, "Wave modifiers", "waves.html", slug(m.id), m.id, m.d);
      const fields = Object.entries(m.f)
        .map(([k, v]) => {
          const label = C.FIELD_LABEL[k] || k;
          if (v === true) return `<div class="per">${esc(label)}</div>`;
          return `<div class="per">${esc(label)} <span class="tot">${pct(v)}</span></div>`;
        })
        .join("");
      return `<div class="row" id="${slug(m.id)}" style="--stripe:var(--epic)" data-hay="${hay(m.id, m.n, m.d)}">
        <div class="r-name" data-anchor><span>${esc(m.n)}</span><span class="r-key">${esc(m.id)}</span></div>
        <div class="r-desc">${esc(m.d)}</div>
        <div class="r-meta">${fields}</div>
      </div>`;
    })
    .join("\n      ");

  const comps = D.compositions
    .map((c) => {
      idx(c.n, "Designed waves", "waves.html", slug(c.id), c.id, c.d);
      const pool = c.pool
        .map((p) => `<a href="bestiary.html#${slug(p.k)}">${esc(p.k)}</a> <span class="tot">${p.w}</span>`)
        .join(" · ");
      return `<div class="row" id="${slug(c.id)}" style="--stripe:var(--epic)"
        data-hay="${hay(c.id, c.n, c.d, c.pool.map((p) => p.k).join(" "))}">
        <div class="r-name" data-anchor><span>${esc(c.n)}</span><span class="r-key">${esc(c.id)}</span></div>
        <div class="r-desc">
          <div>${esc(c.d)}</div>
          <div class="tot"><b>Answer:</b> ${esc(C.COMP_ANSWER[c.id] || "")}</div>
          <div class="per">${pool}</div>
        </div>
        <div class="r-meta">
          <div class="per">wave size <span class="tot">${pct(c.countMult)}</span></div>
          <div class="per">concurrent cap <span class="tot">${pct(c.maxAliveMult)}</span></div>
          <div class="per">score <span class="tot">${pct(c.scoreMult)}</span></div>
          <div class="dep">from <b>wave ${c.minWave}</b></div>
        </div>
      </div>`;
    })
    .join("\n      ");

  const cc = D.consts.composition;
  const rot = D.consts.bossRotation;

  // The unlock ladder, straight off the dumped UNLOCK_WAVE.
  const ladder = D.enemies
    .filter((e) => e.unlock)
    .sort((a, b) => a.unlock - b.unlock || a.k.localeCompare(b.k))
    .reduce((acc, e) => {
      (acc[e.unlock] ||= []).push(e);
      return acc;
    }, {});

  const ladderRows = Object.entries(ladder)
    .map(
      ([w, list]) =>
        `<tr><td>Wave ${w}</td><td>${list
          .map((e) => `<a href="bestiary.html#${slug(e.k)}">${esc(e.k)}</a> <span class="tot">(weight ${e.weight})</span>`)
          .join(", ")}</td></tr>`
    )
    .join("\n        ");

  const body = `    ${toolbar("Filter modifiers and designed waves…")}

    <h2 id="shape">The shape of a wave</h2>
    <p>
      Enemies spawn over time rather than all at once, against a cap on how many can be alive
      together. Both the count and the cap ramp with the wave number and are scaled by the
      difficulty. Clearing the field ends the wave and opens the upgrade screen.
    </p>
    <p>
      They arrive from just outside the camera's view — the real view, which stops at the map's
      edge, so nothing pops in on screen when you fight near a border. One left far out of sight
      for a few seconds is brought back to just off screen, ahead of where you are heading; a boss
      never is. Once the wave has nothing left to send and three or fewer remain, arrows at the
      screen edge point to them.
    </p>
    <p>
      A wave can also carry <b>one</b> event: a modifier, or a designed roster. Never both — two
      banners at once is two things to read and no time to read either.
    </p>

    <h2 id="unlocks">When each enemy appears</h2>
    <p>
      New types stagger in rather than arriving together, and the weights of the earlier ones were
      trimmed to make room instead of inflating the total number of spawns.
    </p>
    <table>
      <thead><tr><th>From</th><th>Joins the pool</th></tr></thead>
      <tbody>
        ${ladderRows}
      </tbody>
    </table>

    <h2 id="modifiers">Wave modifiers</h2>
    <p>A named rule change on a single wave, announced by a banner before it starts.</p>
    <div class="rows">
      ${mods}
    </div>

    <h2 id="compositions">Designed waves</h2>
    <p>
      A hand-picked roster instead of the usual weighted table. They start from
      <b>wave ${cc.FIRST_WAVE}</b> and roll at about <b>${Math.round(cc.CHANCE * 100)}%</b> on an
      eligible wave, so they stay an event rather than a rotation.
    </p>
    <div class="rows">
      ${comps}
    </div>
    <div class="note">${C.COMP_NOTE}</div>

    <h2 id="elites">Elites</h2>
    <div class="note">${C.ELITES}</div>

    <h2 id="bossrot">Boss waves</h2>
    <p>
      Every tenth wave, in a fixed order: ${rot
        .map((k, i) => `<b>wave ${(i + 1) * 10}</b> is <a href="bosses.html#${slug(k)}">${esc(ENEMY_BY_KEY[k]?.x.boss_name || k)}</a>`)
        .join(", ")}, then it cycles.
    </p>
    ${EMPTY}`;

  return page({
    file: "waves.html",
    title: "Waves",
    lead: "How a wave is built, what can be done to it, and when each enemy joins the pool.",
    toc: [
      { id: "shape", label: "The shape of a wave" },
      { id: "unlocks", label: "When each enemy appears" },
      { id: "modifiers", label: "Wave modifiers" },
      { id: "compositions", label: "Designed waves" },
      { id: "elites", label: "Elites" },
      { id: "bossrot", label: "Boss waves" },
    ],
    body,
  });
}

/* ═══════════════════════════════════════════════════════════════════════
   Achievements
   ═══════════════════════════════════════════════════════════════════ */
function achievementsPage() {
  const rows = D.achievements
    .map((a) => {
      idx(a.n, "Achievements", "achievements.html", slug(a.id), a.id, a.d);
      const meta = [];
      if (a.t > 1) meta.push(`<div class="per">target <b>${a.t.toLocaleString("en")}</b></div>`);
      meta.push(`<div class="tot">${a.scope === "run" ? "single run" : "lifetime"}</div>`);
      if (a.md) meta.push(`<div class="dep flag"><b>HARD only</b></div>`);
      if (a.h) meta.push(`<div class="dep">hidden until earned</div>`);
      meta.push(`<div class="tot"><code>${esc(a.stat)}</code></div>`);
      return `<div class="row" id="${slug(a.id)}" style="--stripe:var(--${
        a.md ? "warn" : a.h ? "epic" : a.scope === "run" ? "rare" : "uncommon"
      })"
        data-hay="${hay(a.id, a.n, a.d, a.stat)}"
        data-hidden="${a.h ? 1 : 0}" data-run="${a.scope === "run" ? 1 : 0}" data-hard="${a.md ? 1 : 0}">
        <div class="r-name" data-anchor><span>${esc(a.n)}</span><span class="r-key">${esc(a.id)}</span></div>
        <div class="r-desc">${esc(a.d)}</div>
        <div class="r-meta">${meta.join("")}</div>
      </div>`;
    })
    .join("\n      ");

  const hidden = D.achievements.filter((a) => a.h).length;
  const hard = D.achievements.filter((a) => a.md).length;
  const bestiary = D.achievements.find((a) => a.id === "ACH_BESTIARY");
  const perRun = D.achievements.filter((a) => a.scope === "run").length;

  const body = `    <div class="counts">
      <div class="count"><b>${D.achievements.length}</b><span>total</span></div>
      <div class="count"><b>${perRun}</b><span>single run</span></div>
      <div class="count"><b>${D.achievements.length - perRun}</b><span>lifetime</span></div>
      <div class="count"><b>${hard}</b><span>HARD only</span></div>
      <div class="count"><b>${hidden}</b><span>hidden</span></div>
    </div>

    ${toolbar("Filter achievements…", [
      { attr: "run", label: "single run" },
      { attr: "hard", label: "HARD only" },
      { attr: "hidden", label: "hidden" },
    ])}

    <div class="note">
      <b>Hidden ones are listed here anyway.</b> A wiki that omits them is a wiki you stop trusting
      the moment you find one it did not mention. They are hidden <em>in the game</em>, which is
      where the surprise belongs.
      <br><br>
      Every one is backed by a counter with a stable id, so progress survives a rename and nothing
      is ever revoked once earned — a reconcile pass grants retroactively but never takes back.
      <br><br>
      <b>Full Bestiary</b> counts ${bestiary ? bestiary.t : "every"} lines: one for every ordinary
      enemy type, the Witchdoctor and the Bonecaller separately, and neither boss — they have
      achievements of their own. A test kills one of each type and checks the target against the
      roster, because twice now new enemies shipped without a line of their own.
    </div>

    <div class="rows">
      ${rows}
    </div>
    ${EMPTY}`;

  return page({
    file: "achievements.html",
    title: "Achievements",
    lead: `All ${D.achievements.length}, hidden ones included, with the counter behind each.`,
    body,
  });
}

/* ═══════════════════════════════════════════════════════════════════════
   Systems
   ═══════════════════════════════════════════════════════════════════ */
function systemsPage() {
  const combat = C.COMBAT.map((c) => `<h3 id="${slug(c.h)}">${esc(c.h)}</h3>\n    <p>${c.p}</p>`).join("\n    ");
  for (const c of C.COMBAT) idx(c.h, "Systems", "systems.html", slug(c.h), "", c.p.replace(/<[^>]+>/g, ""));

  const tiers = C.KILL_TIERS.map(
    (k) => `<tr><td>${esc(k.name)}</td><td><code>×${k.at}</code></td><td>${
      k.t === 1 ? "where every combo starts — nothing is promoted into it" : "promotes here: a banner, and the next rung of the streak"
    }</td></tr>`
  ).join("\n        ");

  const body = `    <h2 id="combat">Combat</h2>
    ${combat}

    <h2 id="combo">The combo ladder</h2>
    <p>
      Consecutive hits inside a window. Several cards scale off it, and the audio tracks it — every
      kill fires a confirm pitched to your current tier, so the sound of a run climbing is
      information rather than decoration.
    </p>
    <table>
      <thead><tr><th>Tier</th><th>At</th><th></th></tr></thead>
      <tbody>
        ${tiers}
      </tbody>
    </table>

    <h2 id="score">Score</h2>
    <p>${C.SCORE}</p>

    <h2 id="sound">Sound</h2>
    <div class="note">${C.AUDIO_NOTE}</div>

    <h2 id="tooling">How this wiki is built</h2>
    <p>
      Two commands, run from this site's own repository against a checkout of the game.
      <code>tools/dump_main.lua</code> runs under LÖVE, loads the game's own modules, and writes
      every definition table to JSON — including the ones that are
      <em>file-local</em> and therefore invisible to an ordinary dumper. Those are recovered
      through <code>debug.getupvalue</code>, which is how unlock waves, spawn weights, stack caps
      and prerequisites reach this site without anyone retyping them.
    </p>
    <p>
      <code>tools/build.mjs</code> then renders <code>docs/</code> from that JSON plus the
      hand-written prose in <code>content.mjs</code>. The split is the point: if a fact could have
      been derived and was typed instead, it is a bug waiting to drift. An earlier version of this
      reference kept those tables by hand, and three of them had already gone stale.
    </p>
    <p>
      Enemy portraits are not copied out of the sprite folder. ${D.enemies.length - new Set(D.enemies.map((e) => e.sheet)).size}
      of the ${D.enemies.length} types borrow another one's art, so <code>tools/portraits_main.lua</code> renders each frame through
      the same recolour shader the game uses at draw time — a hue rotation in YIQ, or a multiply
      tint for the sprites with no chroma to rotate. Copying the PNGs would produce a bestiary in
      which a third of the roster is the same picture repeated.
    </p>`;

  return page({
    file: "systems.html",
    title: "Systems",
    lead: "The machinery underneath: how damage resolves, how score is earned, how the audio tracks a run, and how these pages are generated.",
    toc: [
      { id: "combat", label: "Combat" },
      { id: "combo", label: "The combo ladder" },
      { id: "score", label: "Score" },
      { id: "sound", label: "Sound" },
      { id: "tooling", label: "How this wiki is built" },
    ],
    body,
  });
}

/* ═══════════════════════════════════════════════════════════════════════
   Write
   ═══════════════════════════════════════════════════════════════════ */
mkdirSync(join(DOCS, "assets", "img"), { recursive: true });

const PAGES = {
  "index.html": homePage,
  "guide.html": guidePage,
  "bestiary.html": bestiaryPage,
  "bosses.html": bossesPage,
  "cards.html": cardsPage,
  "abilities.html": abilitiesPage,
  "classes.html": classesPage,
  "waves.html": wavesPage,
  "achievements.html": achievementsPage,
  "systems.html": systemsPage,
};

// Rendered in order; the search index accumulates as a side effect, so it is
// written last.
const rendered = {};
for (const [file, fn] of Object.entries(PAGES)) rendered[file] = fn();

for (const [file, html] of Object.entries(rendered)) writeFileSync(join(DOCS, file), html, "utf8");

writeFileSync(
  join(DOCS, "assets", "search.js"),
  "/* Generated by Tools/wiki/build.mjs — do not edit. */\nwindow.SEARCH_INDEX=" +
    JSON.stringify(INDEX) +
    ";\n",
  "utf8"
);

for (const f of ["wiki.css", "wiki.js"]) {
  copyFileSync(join(HERE, "src", f), join(DOCS, "assets", f));
}

// GitHub Pages runs Jekyll by default, which skips files and folders beginning
// with an underscore and can rewrite what it thinks is a template. This is a
// plain static site; .nojekyll turns all of that off.
writeFileSync(join(DOCS, ".nojekyll"), "", "utf8");

const imgs = readdirSync(join(DOCS, "assets", "img")).filter((f) => f.endsWith(".png"));
console.log(
  `${Object.keys(PAGES).length} pages · ${INDEX.length} search entries · ${imgs.length} portraits · ${
    D.upgrades.length
  } cards, ${D.enemies.length} enemies, ${D.achievements.length} achievements`
);

// A portrait referenced by the bestiary but never generated is a broken image
// on a published page, which is exactly the kind of thing nobody notices.
const missing = D.enemies.filter((e) => !imgs.includes(e.k + ".png")).map((e) => e.k);
if (missing.length) {
  console.error("MISSING PORTRAITS: " + missing.join(", "));
  process.exitCode = 1;
}
